### ISSUE TITLE
[Bug] Autoupdate not working

### ISSUE THREAD

**Issue by Splike** [xanderfrangos/twinkle-tray#11] opened 2020-01-31 16:27 UTC
Clicking the "update" button in the pop-up window will do nothing.

Opening the settings and clicking "update", will have the text stuck at "Downloading update..."

![Screenshot 2020-01-31 17 22 42](https://user-images.githubusercontent.com/7159527/73555903-b26f5500-444e-11ea-9abb-d8c80b1f82d2.png)

Tried running the program as admin. Same results as above.

**Comment by xanderfrangos** [comment] 2020-01-31 17:29
Try going to **%appdata%\twinkle-tray** in the Windows file explorer and check if a file called update.exe is there. If so, delete it and try the auto-updater again.

**Comment by Splike** [comment] 2020-01-31 19:20
So I deleted `update.exe` and tried to update again. `update.exe` reappears and nothing happens.
It's stuck like before.

![Twinkle Tray Update](https://user-images.githubusercontent.com/7159527/73567629-0b4ae780-4467-11ea-8166-e7347698c9bb.png)

**Comment by Splike** [comment] 2020-01-31 19:24
It seems like `update.exe` is never executed. Manually executing the file starts the update, but ends in the following error:

![Screenshot 2020-01-31 20 22 05](https://user-images.githubusercontent.com/7159527/73567945-b2c81a00-4467-11ea-93d9-2c40847b54db.png)

**Comment by xanderfrangos** [comment] 2020-02-01 15:03
Do you use any antivirus software or do you have any special characters in your Windows username? It looks like something is stopping the updater from running correctly. For now, you'll probably have to manually download/run the update from the [Releases page](https://github.com/xanderfrangos/twinkle-tray/releases). If you get any errors, uninstall the app and reinstall. In the future, I'll try to add code to better handle auto-update errors.

**Comment by Splike** [comment] 2020-02-01 16:55
I use no special antivirus software (Only Windows Defender) and my username only contains characters within [A-Z] and [a-z].

After shutting down my PC for the night and rebooting it in the morning, the `update.exe` file is now automatically being run. I know this, because the error I posted above pops up automatically upon logging into my windows user.

I will update to v1.8.1 manually via the releases page for now.

**Comment by Splike** [comment] 2020-02-07 15:27
I just updated from v1.8.1 to v1.8.4, by having to manually run `update.exe`. No error this time, but the update file isn't executed at all, when I try to run the update from the twinkle-tray pop-up window or the update button in the settings.

**Comment by Splike** [comment] 2020-02-13 19:32
Same experince from v1.8.4 to v1.8.5.
I have to manually run `update.exe`. But it updates without issues.

**Comment by xanderfrangos** [comment] 2020-02-16 15:23
I'll see what I can do to improve error handling for updates in v1.9.0, but I haven't been able to recreate the issue.

**Comment by xanderfrangos** [comment] 2020-04-17 06:31
@Splike I have a new version just about ready, which includes improvements to the update process. Do you mind testing with the new version from the link below? It's an update for version v1.9.0. Once installed, it'll ask you to "update" to v1.8.6. Let me know if it's able to install v1.8.6 without issue.

https://1drv.ms/u/s!AiWKFpjcSKRQhdJ4rhD3IrXGl3_HXA?e=sqBemO

**Comment by xanderfrangos** [comment] 2020-04-26 14:11
@Splike Just wanted to check in one more time before I close the issue. Have you had a chance to check if the update process for v1.9.0 has helped?

**Comment by Splike** [comment] 2020-04-26 15:02
So I installed the 1.9.0-rc1 build and tried to upgrade it to 1.9.1.
After clicking the download and install button, the button will after a short while contain an "!" icon and nothing more will happen.

![Screenshot 2020-04-26 17 00 01](https://user-images.githubusercontent.com/7159527/80311386-aee63280-87df-11ea-8962-e9d6e2b53f12.png)

**Comment by xanderfrangos** [comment] 2020-04-26 15:40
@Splike Okay, thanks for trying it out. The icon means that either:
- The update file wasn't downloaded.
- The update file is incomplete.
- The update file couldn't be run.

If you don't mind, attempting to update from [this build](https://1drv.ms/u/s!AiWKFpjcSKRQhdJ7u9l7kEBVkSKL4A?e=buu6jL) will spit out which exact error it's running in to. Hopefully that will point me in the right direction.

**Comment by Splike** [comment] 2020-04-26 17:56
Hope this helps:

![Screenshot 2020-04-26 19 55 31](https://user-images.githubusercontent.com/7159527/80315468-06909800-87f8-11ea-8603-e389e679bc46.png)

**Comment by xanderfrangos** [comment] 2020-04-26 19:05
@Splike Thanks! It sort of helps. That was an error I was hoping not to get. I can't reproduce that error at all, so I'm working in the dark on this. 

I've put together two potential fixes. Let me know if either of them work.
- Fix 1: https://1drv.ms/u/s!AiWKFpjcSKRQhdJ8VTJ0vKn47ib00A?e=0sBsch
- Fix 2: https://1drv.ms/u/s!AiWKFpjcSKRQhdJ9YYuRabKCY_YtsA?e=YCejD7

If neither of these work, I'll unfortunately have to give up. My only suggestion at that point would be to use the Windows Store version.

**Comment by Splike** [comment] 2020-04-26 19:25
I tried both Fix 1 and Fix 2. Both of them updated without issue!

**Comment by xanderfrangos** [comment] 2020-04-26 19:31
Awesome! 🎉🥳🎊 Thanks for all the help getting this figured out. After the next update, you shouldn't have issues going forward.

**Comment by Splike** [comment] 2020-04-26 19:33
Great to hear! You're very welcome. Thanks for fixing the issue :)

**Closed** 2020-04-30 14:21 UTC
