### ISSUE TITLE
Twinkle Tray is litters AppData/Local/Temp with .tmp.node files

### ISSUE THREAD

**Issue by TiborGY** [xanderfrangos/twinkle-tray#542] opened 2023-01-28 21:00 UTC
Dear devs,

I have been using TT for quite a while, and I have just had to delete ~1 GiB of litter that TT had left in my Temp folder, with names like `4a86bdff-c53a-45b7-945b-8371d7e17736.tmp.node`, and file sizes between 100 and 700 KiB.

It would be nice if TT would stop leaving these files in AppData/Local/Temp.

**Comment by 205g0** [comment] 2023-02-21 06:35
nice find, how do you know they are from Twinkle Tray (and yeah, I just deleted also 1.5 GB of these files haha)

**Comment by DRSAgile** [comment] 2023-02-28 09:20
Those files are definitely from TT. I installed it yesterday and the time for those temporary Node files matches. I only have 2.5 MB of them, though, but let's see if the files will be added daily.

Utilities like this are small and simple by the concept, but drag huge baggage with themselves. In this case, [Electron](https://electronjs.org/), [Node.js](https://nodejs.org/), [node-ddcci](https://github.com/hensm/node-ddcci), and [win32-displayconfig](https://github.com/djsweet/win32-displayconfig), even though the utility itself requires only a tiny bit of functionality of those projects. As a result, it takes a whopping 84 MB even compressed and becomes so complicated that some "leaks" like you describe are unavoidable.

The main problem of the modern programming is that there is no way to effectively strip down the rubbish you do not actually need. If it was possible, this utility would occupy like a couple orders of magnitude less space than it does now.

Back on the topic: the author does not seem to be available to maintain the project, including fixing the issue you posted about it. The licence allows others to fork the project to it themselves, but it is a commitment, so I am not seeing people that can do this (I can not, either).

**Comment by xanderfrangos** [comment] 2023-03-08 21:11
Hi all,

While it's certainly possible that Twinkle Tray is doing that (as it uses NodeJS), I am not aware of a way to determine how many of those are coming from Twinkle Tray or another Node/Electron app. I (obviously) have Twinkle Tray running on my PCs all of the time, and I'm not seeing anywhere near the number of `.tmp.node` files you're referring to. There are dozens of software that could produce `.tmp.node` files (Adobe CC suite, Visual Studio Code, Slack, Teams, Discord, Logitech drivers, and NVIDIA drivers, just to name a few). 

If someone can reliably reproduce Twinkle Tray specifically producing a massive quantity of `.tmp.node` files, there isn't much I can look into. I will keep this in mind in the event that I come across a possible source of this issue.

**Comment by xanderfrangos** [comment] 2023-03-08 22:10
> Utilities like this are small and simple by the concept, but drag huge baggage with themselves. In this case, [Electron](https://electronjs.org/), [Node.js](https://nodejs.org/), [node-ddcci](https://github.com/hensm/node-ddcci), and [win32-displayconfig](https://github.com/djsweet/win32-displayconfig), even though the utility itself requires only a tiny bit of functionality of those projects. As a result, it takes a whopping 84 MB even compressed and becomes so complicated that some "leaks" like you describe are unavoidable.
>
> The main problem of the modern programming is that there is no way to effectively strip down the rubbish you do not actually need. If it was possible, this utility would occupy like a couple orders of magnitude less space than it does now.

@DRSAgile 

Electron is the vast majority of the size. `node-ddcci` and `win32-displayconfig` are actually tiny C++ libraries. The compiled binaries are less than 1MB combined. That said, Twinkle Tray is not described anywhere as being lightweight, nor do I hide the fact that it is made with Electron. Electron offered me the ease/flexibility necessary to create and maintain this app in my limited free time. Twinkle Tray wouldn't exist without Electron. 

There are plenty of other options that are significantly lighter and more utilitarian, such as Monitorian, ClickMonitorDDC, and ControlMyMonitor. Those apps are all excellent in different ways, as is Twinkle Tray. Twinkle Tray offers many features that are locked behind a subscription for Monitorian and a more "native" appearance than other brightness control apps. Different strokes for different folks.

**Comment by DRSAgile** [comment] 2023-03-09 10:11
If I was not clear enough from my previous post, I was not suggesting that it is your power to easily make the utility lightweight; it is not your issue, you have made a great utility. On the contrary, I was trying to explain that there are no ways to effectively do it.

That said, in the future, IDEs will start offering deeper heuristic and even neural networks-powered options. This will finally allow relinking components of your project and recompile it only with the parts that are actually necessary, with not a single byte excessive. Such software technologies will be able to work even if you do not have access to the source code: right with the binaries.

Things will not go back to the old days when I was able to write an assembly code that was doing quite a lot in just a few kilobytes of memory, but still much better than now on average.

But until then, we will still have to bear lots of luggage and/or bring ugly dependences like the necessity to install runtime Java environment or a specific version of .Net.

**Comment by DRSAgile** [comment] 2023-03-09 10:31
> Hi all,
> 
> While it's certainly possible that Twinkle Tray is doing that (as it uses NodeJS), I am not aware of a way to determine how many of those are coming from Twinkle Tray or another Node/Electron app. I (obviously) have Twinkle Tray running on my PCs all of the time, and I'm not seeing anywhere near the number of `.tmp.node` files you're referring to. There are dozens of software that could produce `.tmp.node` files (Adobe CC suite, Visual Studio Code, Slack, Teams, Discord, Logitech drivers, and NVIDIA drivers, just to name a few).
> 
> Unless someone can reliably reproduce Twinkle Tray producing a massive quantity of `.tmp.node` files, there isn't much I can look into. I will keep this in mind in the event that I come across a possible source of this issue.

Xander, as I promised in my first comment on this, I tracked the ".node.tmp" on my side.

Those files are definitely from the utility, as they contain its name as well as a list of monitor-related methods of the objects that are used (`monitorFriendlyDeviceName`, `monitorDev`, `indirect virtual`, et cetera).

After more than a week, there are still less than 3 MB of these files in my temporary directory, so it is not an issue in my case.

However, my environment is different from that of the original poster, so it may not tell the full story.

But even my case might be enough to solve it, since I got three copies of exact same 650 KB ".node.tmp", including two of them at the exact same timestamp (a few other ".node.tmp" files are unique).

I can imagine that if something goes wrong, those files could multiply in a crazier manner.

So I guess that if you will be able to find the exact reason why Node.js creates three copies of the same temporary file instead of just one, the issue will be solved for the original poster, too.

**Comment by Phillipus** [comment] 2024-06-29 15:49
Twinkle Tray is a nice app but I had to uninstall it because it's creating a huge amount of these `.tmp` files and not cleaning up when the app exits. So if you are logout or restart Windows then another dozen or so of these files are created each time.

And yes, they are definitely created by TT. You can see that if you try to delete one:

![Image 001](https://github.com/xanderfrangos/twinkle-tray/assets/600504/a7f6aaad-9802-4cec-9f37-3f685f666b45)

**Comment by Phillipus** [comment] 2024-06-30 08:56
More info here - https://github.com/electron/electron/issues/10139

Someone suggests adding `"asarUnpack": "**/*.node"` to the `"build":` section of the config file.

**Comment by xanderfrangos** [comment] 2024-07-24 16:19
It appears that when Twinkle Tray didn't properly quit (e.g. crashing or terminating the process), the `.tmp.node` files didn't get cleaned up. I've released v1.15.5 and v1.16.0-beta7 with the suggestion @Phillipus pointed out. It slightly increases the install size, but should completely fix this bug and may help with permissions/antivirus issues some users have.

**Comment by Phillipus** [comment] 2024-10-21 16:08
I'm using v1.16.2 and this issue seems to be fixed. There is only one `.tmp` file created which is deleted when TT quits. Thanks!

**Comment by xanderfrangos** [comment] 2024-10-21 23:43
This should actually be good as of v1.15.5, so I'll go ahead and close this.

**Closed by xanderfrangos** 2024-10-21 23:43 UTC
