### ISSUE TITLE
[Feature request] Auto Adjustment at specific time

### ISSUE THREAD

**Issue by Lolihunter1337** [xanderfrangos/twinkle-tray#3] opened 2020-01-13 20:10 UTC
Would be nice if you can set times where it Adjust the brightness to a certain value

**Comment by xanderfrangos** [comment] 2020-01-18 23:46
Thanks for the suggestion! I've implemented it in [v1.7.0](https://github.com/xanderfrangos/twinkle-tray/releases). Give it a try and let me know if you have any other feedback.

**Comment by jordi-7** [comment] 2020-01-19 00:23
I've tried this new feature and I find it really useful but I think it could be improved if I could also choose a specific monitor when configuring a new time.

**Comment by Lolihunter1337** [comment] 2020-01-19 00:34
i just tried it. it doesnt work for me. ( would be also nice if you can type in any time instead of having that drop-down menu )

**Comment by MiraiSubject** [comment] 2020-01-19 00:36
Over on my side I can't get this feature to work at all. Like @Lolihunter1337 said it would be nice if you could adjust the time in minute increments. 

Putting in 1:45 am, setting the time in windows to 1:44 am waiting one minute till 1:45 doesn't change the brightness of the monitor at all. Manually change the brightness does work as intended in this version.

**Comment by xanderfrangos** [comment] 2020-01-19 00:38
It doesn't kick in immediately if you're already past the time it's scheduled for. Try enabling "Check at app startup" and restart Twinkle Tray. Since you guys are expecting it to activate immediately, I'll change how that works.

**Comment by xanderfrangos** [comment] 2020-01-19 15:09
[v1.7.1](https://github.com/xanderfrangos/twinkle-tray/releases) is out with time-of-day rules taking immediate effect. I'll consider changing the time input to allow for specific times, but it's not high on my priorities. 

@jordi-7 Regarding individual monitor brightness, I suggest using the "Normalize Brightness" setting. It's a very useful option for keeping the brightness of each display how you want them as they all get dimmer/brighter. For example, you can set your middle monitor with a higher max brightness so it's always a little brighter than the others.

**Comment by jordi-7** [comment] 2020-01-19 15:23
Normalizing brightness helps but it's not enough for my usecase. My main monitor is capable of a lot of brightness so it is the one that I want to adjust based on the time of the day. My second monitor is not bright so I want it all the time at maximum brightness.
Per monitor control would be awesome but I understand if my use case is not common. As I said, normalizing brightess works well enough. A suggestion would be allowing to set the minimum brightess the same as the maximum, right now it forces a 10% difference.

**Comment by xanderfrangos** [comment] 2020-01-19 16:35
I'll add a toggle so you can control the brightness per display per time-of-day rule. I just don't want the default options to be too complicated.

**Comment by xanderfrangos** [comment] 2020-01-20 13:55
@jordi-7 v1.7.2 (and now v1.7.3) has added the option to configure the time-of-day brightness per display. Let me know if it works well for you.

**Comment by jordi-7** [comment] 2020-01-20 14:24
Works perfectly!

**Comment by xanderfrangos** [comment] 2020-01-20 16:11
Awesome! I'm closing the issue as the feature is now complete. If there's any other feedback or requests, feel free to open a new issue.

**Closed by xanderfrangos** 2020-01-20 16:11 UTC
Labels: enhancement
